// ==========================================
// AstroMachine Mobile - Dados Seed Locais
// ==========================================

import { Product, Service } from '../types';

export const seedProducts: Product[] = [
  {
    id: 'seed-prod-1',
    name: 'Build Andromeda',
    description: 'PC gamer de alto desempenho com temática da galáxia Andrômeda. RTX 4070, Ryzen 7 7800X3D, 32GB DDR5.',
    price: 8999.90,
    imageUrl: '',
    category: 'high-end',
    specs: 'RTX 4070 | Ryzen 7 7800X3D | 32GB DDR5 | 1TB NVMe | Water Cooler 240mm',
    inStock: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'seed-prod-2',
    name: 'PC Orion',
    description: 'Workstation robusta inspirada na constelação de Orion. Ideal para criadores de conteúdo e streamers.',
    price: 12499.90,
    imageUrl: '',
    category: 'workstation',
    specs: 'RTX 4080 | Ryzen 9 7950X | 64GB DDR5 | 2TB NVMe | Custom Loop',
    inStock: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'seed-prod-3',
    name: 'Nebula Prime',
    description: 'Build intermediária com visual nebuloso e LEDs RGB sincronizados. Perfeita para o gamer moderno.',
    price: 5999.90,
    imageUrl: '',
    category: 'mid-range',
    specs: 'RTX 4060 Ti | Ryzen 5 7600X | 16GB DDR5 | 512GB NVMe | Air Cooler',
    inStock: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'seed-prod-4',
    name: 'Exoplaneta X',
    description: 'Setup compacto Mini-ITX com design futurista inspirado em exoplanetas.',
    price: 7499.90,
    imageUrl: '',
    category: 'compact',
    specs: 'RTX 4070 | Ryzen 7 7700X | 32GB DDR5 | 1TB NVMe | Mini-ITX Case',
    inStock: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'seed-prod-5',
    name: 'Supernova Elite',
    description: 'O top de linha da AstroMachine. Performance explosiva com componentes de ponta.',
    price: 19999.90,
    imageUrl: '',
    category: 'extreme',
    specs: 'RTX 4090 | Ryzen 9 7950X3D | 128GB DDR5 | 4TB NVMe | Custom Loop Hardline',
    inStock: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'seed-prod-6',
    name: 'Cosmos Starter',
    description: 'Entrada ideal para quem está começando no universo gamer. Custo-benefício estelar.',
    price: 3499.90,
    imageUrl: '',
    category: 'entry',
    specs: 'RTX 4060 | Ryzen 5 5600 | 16GB DDR4 | 512GB NVMe | Air Cooler',
    inStock: true,
    createdAt: new Date().toISOString(),
  },
];

export const seedServices: Service[] = [
  {
    id: 'seed-svc-1',
    name: 'Pintura Galáxia',
    description: 'Pintura aerografada personalizada com temática de galáxias e nebulosas no gabinete.',
    price: 899.90,
    estimatedHours: 48,
    category: 'visual',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'seed-svc-2',
    name: 'RGB Cósmico',
    description: 'Instalação de iluminação RGB sincronizado com efeitos de aurora boreal e pulsação estelar.',
    price: 349.90,
    estimatedHours: 4,
    category: 'iluminação',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'seed-svc-3',
    name: 'Gravação Lunar',
    description: 'Gravação a laser em painéis laterais com motivos lunares ou constelações.',
    price: 599.90,
    estimatedHours: 24,
    category: 'personalização',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'seed-svc-4',
    name: 'Montagem Premium',
    description: 'Montagem completa com cable management profissional e teste de estresse de 72h.',
    price: 499.90,
    estimatedHours: 8,
    category: 'montagem',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'seed-svc-5',
    name: 'Overclock Estelar',
    description: 'Ajuste fino de overclock em CPU e GPU com monitoramento térmico.',
    price: 299.90,
    estimatedHours: 6,
    category: 'performance',
    createdAt: new Date().toISOString(),
  },
];
